In [1]:
import numpy as np

## The Basics

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get dimensions
a.ndim

1

In [5]:
b.ndim

2

In [6]:
# Get Shape
a.shape

(3,)

In [7]:
b.shape

(2, 3)

In [8]:
# Get type
a.dtype

dtype('int32')

In [9]:
b.dtype

dtype('float64')

In [10]:
# Get size
a.itemsize

4

In [11]:
b.itemsize

8

In [12]:
# get total size
a.nbytes

12

In [13]:
b.nbytes

48

## Accessing/Changing specific elements, rows, columns, etc

In [14]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [15]:
# get a specific element [r,c]
a[0,2]

3

In [16]:
# get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
# get a specific column
a[:,2]

array([ 3, 10])

In [18]:
# getting a little more fancy (startindex:endindex:stepsize)
a[0, 1:6:2]

array([2, 4, 6])

#### 3-d array example

In [19]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
# get specfic element ( works outside in)
b[0,1,1]

4

In [21]:
# replace
b[:,1,:] = [[1,2],[3,4]]
print(b)

[[[1 2]
  [1 2]]

 [[5 6]
  [3 4]]]


## Initializing Different Types of Arrrays

In [22]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [24]:
# Any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [25]:
# Any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [26]:
# Random decimal numbers
np.random.random_sample(a.shape)

array([[0.76376506, 0.17004426, 0.951105  , 0.89008879, 0.79810466,
        0.73764581, 0.80576502],
       [0.87172183, 0.76535776, 0.303129  , 0.79649039, 0.07138402,
        0.43535414, 0.25229949]])

In [27]:
# Random Integer values
np.random.randint(4,7, size=(3,3))

array([[6, 4, 6],
       [6, 6, 4],
       [5, 5, 4]])

In [28]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
np.random.randint(2, size=(3,3))

array([[0, 1, 1],
       [0, 1, 0],
       [0, 0, 0]])

In [56]:
# repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [61]:
r1 = np.ones((5,5))
print(r1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [62]:
r1[1,1:4] = 0
r1[3,1:4] = 0
r1[2,1:4] = 0
r1[2,2] = 9
print(r1)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays!!!

In [68]:
a = np.array([1,2,3])
b=a
b[0]=100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [67]:
a = np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)
print(b)

[1 2 3]
[100   2   3]


### Mathematics

In [70]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [71]:
a+2

array([3, 4, 5, 6])

In [72]:
a-2

array([-1,  0,  1,  2])

In [73]:
a*2

array([2, 4, 6, 8])

In [74]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [75]:
a%2

array([1, 0, 1, 0], dtype=int32)

In [78]:
b = np.array([1,0,1,0])
a+b

array([6, 6, 8, 8])

In [81]:
a

array([5, 6, 7, 8])

In [83]:
a ** 2

array([25, 36, 49, 64], dtype=int32)

In [84]:
# take the sin
np.sin(a)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

In [85]:
np.cos(a)

array([ 0.28366219,  0.96017029,  0.75390225, -0.14550003])

### Linear Algebra

In [93]:
# matrix multiplication
a= np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [94]:
# find the determinant
c=np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [95]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
np.min(stats, axis=1)

array([1, 4])

### Reorganizing Arrays

In [98]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

(2, 4)


In [101]:
after = before.reshape((8,1))
print(after.shape)

(8, 1)


In [104]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [109]:
# Horizontal stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous 

### Load Data from file

In [113]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

### Boolean Masking and Advanced Indexing

In [116]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [117]:
# You can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [119]:
np.any(filedata>50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [121]:
np.all(filedata>50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [123]:
np.all(filedata>50, axis=1)

array([False, False, False])

In [125]:
(~((filedata > 50) & (filedata <100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])