In [1]:
import numpy as np

## The Basics

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [12]:
# Get dimensions
a.ndim

1

In [13]:
b.ndim

2

In [14]:
# Get Shape
a.shape

(3,)

In [15]:
b.shape

(2, 3)

In [16]:
# Get type
a.dtype

dtype('int32')

In [17]:
b.dtype

dtype('float64')

In [18]:
# Get size
a.itemsize

4

In [22]:
b.itemsize

8

In [20]:
# get total size
a.nbytes

12

In [21]:
b.nbytes

48

## Accessing/Changing specific elements, rows, columns, etc

In [30]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [31]:
# get a specific element [r,c]
a[0,2]

3

In [33]:
# get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [34]:
# get a specific column
a[:,2]

array([ 3, 10])

In [36]:
# getting a little more fancy (startindex:endindex:stepsize)
a[0, 1:6:2]

array([2, 4, 6])

#### 3-d array example

In [38]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [44]:
# get specfic element ( works outside in)
b[0,1,1]

4

In [48]:
# replace
b[:,1,:] = [[1,2],[3,4]]
print(b)

[[[1 2]
  [1 2]]

 [[5 6]
  [3 4]]]


## Initializing Different Types of Arrrays

In [58]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [60]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [62]:
# Any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [66]:
# Any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [72]:
# Random decimal numbers
np.random.random_sample(a.shape)

array([[0.68829761, 0.81235503, 0.2453277 , 0.62120086, 0.18500496,
        0.05593829, 0.47506595],
       [0.67021193, 0.39563415, 0.21228515, 0.10583223, 0.82234612,
        0.80593607, 0.65836072]])

In [91]:
# Random Integer values
np.random.randint(4,7, size=(3,3))

array([[6, 5, 6],
       [4, 6, 5],
       [6, 4, 5]])

In [97]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])